version: 2.1

executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.6.3-node
        environment:
          - BUNDLER_VERSION: 2.0.2
          - RAILS_ENV: 'test'
          - RAILS_ENV: test
          - PGHOST: 127.0.0.1
          - PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_DB: app_test

commands:
  setup_database:
    steps:
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: Database setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }}-{{ .Branch }}
            - gem-cache
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.0.2
            bundle check --path=vendor/bundle || bundle install --path vendor/bundle --clean --jobs 4 --retry 3
      - save_cache:
          paths:
            - ./vendor/bundle
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - setup_database
      - persist_to_workspace:
          root: .
          paths: vendor/bundle
  test:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }}-{{ .Branch }}
            - gem-cache
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.0.2
            bundle check --path=vendor/bundle || bundle install --path vendor/bundle --clean --jobs 4 --retry 3
      - save_cache:
          paths:
            - ./vendor/bundle
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run rails best practice
          command: bundle exec rails_best_practices
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Run rspec
          command: |
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
